#!/bin/sh
#
# 	Instant Wordpress!
# 	------------------
# 	My script for installing the latest version of WordPress plus a number of plugins I find useful.
#		
# 	To use this script, go to the directory you want to install Wordpress to in the terminal and run this command:
# 
# 	curl scripts.snaptortoise.com/wordpress | sh
#
# 	There you go.
#


# Latest version of WP
echo "Fetching WordPress...";
wget --quiet http://wordpress.org/latest.zip;
unzip -q latest.zip;

# WordPress SEO
echo "Fetching WordPress SEO plugin...";
wget --quiet http://downloads.wordpress.org/plugin/wordpress-seo.1.4.19.zip;
unzip -q wordpress-seo.1.4.19.zip;
mv all-in-one-seo-pack wordpress/wp-content/plugins/

# Sitemap Generator
echo "Fetching Google Sitemap Generator plugin...";
wget --quiet http://downloads.wordpress.org/plugin/google-sitemap-generator.zip;	
unzip -q  google-sitemap-generator.zip;	
mv google-sitemap-generator wordpress/wp-content/plugins/

# Better WP Security
echo "Fetching Better WP Security plugin...";
wget --quiet http://downloads.wordpress.org/plugin/better-wp-security.3.5.6.zip;
unzip -q  better-wp-security.3.5.6.zip;
mv secure-wordpress wordpress/wp-content/plugins/

# Advanced Custom Fields
echo "Fetching ACF plugin...";
wget --quiet http://downloads.wordpress.org/plugin/advanced-custom-fields.zip;
unzip -q  advanced-custom-fields.zip;
mv hierarchy wordpress/wp-content/plugins/

# Image Widgets (Why isn't this standard?)
echo "Fetching Image Widget plugin...";
wget --quiet http://downloads.wordpress.org/plugin/image-widget.zip;
unzip -q  image-widget.zip;
mv image-widget wordpress/wp-content/plugins/

# W3 Total Cache 
echo "Fetching W3 Total Cache...";
wget --quiet http://downloads.wordpress.org/plugin/w3-total-cache.zip
unzip -q  w3-total-cache.zip;
mv w3-total-cache wordpress/wp-content/plugins/

# Register Plus Redux (Good for membership-style sites)
# echo "Fetching Register Plus Redux...";
# wget --quiet http://downloads.wordpress.org/plugin/register-plus-redux.zip
# unzip -q register-plus-redux.zip
# mv register-plus-redux wordpress/wp-content/plugins/

# Regenerate Thumbnails (good for when you need to make custom sizes)
echo "Fetching Regenerate Thumbnails...";
wget --quiet http://downloads.wordpress.org/plugin/regenerate-thumbnails.zip
unzip -q regenerate-thumbnails.zip
mv regenerate-thumbnails wordpress/wp-content/plugins/


# WordPress Importer
echo "Fetching WordPress Importer...";
wget --quiet http://downloads.wordpress.org/plugin/wordpress-importer.zip
unzip -q wordpress-importer.zip
mv wordpress-importer wordpress/wp-content/plugins/


# Simple Page Ordering
echo "Fetching Simple Page Ordering...";
wget --quiet http://downloads.wordpress.org/plugin/simple-page-ordering.zip
unzip -q simple-page-ordering.zip
mv simple-page-ordering wordpress/wp-content/plugins/

# FeedWordPress
echo "FeedWordPress...";
wget --quiet http://downloads.wordpress.org/plugin/feedwordpress.zip
unzip -q feedwordpress.zip
mv feedwordpress wordpress/wp-content/plugins/

# BackupWPup
echo "BackupWPup...";
wget --quiet http://downloads.wordpress.org/plugin/backwpup.zip
unzip -q backwpup.zip
mv backwpup wordpress/wp-content/plugins/


# Cleanup
echo "Cleaning up temporary files and directories...";
rm *.zip


# Move stuff into current directory
mv wordpress/* .;
rm -rf wordpress;


# Disable the built-in file editor because it's a hacking vector and I hate it
echo "Disabling file editor...";
echo "
/* Disable the file editor */
define(‘DISALLOW_FILE_EDIT’, true);" >> wp-config-sample.php

echo "Done!";
