#!/bin/sh
#
# 	Instant Wordpress!
# 	------------------
# 	My script for installing the latest version of WordPress plus a number of plugins I find useful.
#		
# 	To use this script, go to the directory you want to install Wordpress to in the terminal and run this command:
# 
# 	curl https://raw.githubusercontent.com/tnog/wordpress-quick-install/master/wordpress | sh
#
# 	There you go.
#


# Latest version of WP
echo "Fetching WordPress...";
wget --quiet http://wordpress.org/latest.zip;
unzip -q latest.zip;

# WordPress SEO
#echo "Fetching WordPress SEO plugin...";
#wget --quiet http://downloads.wordpress.org/plugin/wordpress-seo.1.4.19.zip;
#unzip -q wordpress-seo.1.4.19.zip;
#mv wordpress-seo wordpress/wp-content/plugins/

# Better WP Security
#echo "Fetching Better WP Security plugin...";
#wget --quiet http://downloads.wordpress.org/plugin/better-wp-security.3.5.6.zip;
#unzip -q  better-wp-security.3.5.6.zip;
#mv better-wp-security wordpress/wp-content/plugins/

# Advanced Custom Fields
#echo "Fetching ACF plugin...";
#wget --quiet http://downloads.wordpress.org/plugin/advanced-custom-fields.zip;
#unzip -q  advanced-custom-fields.zip;
#mv advanced-custom-fields wordpress/wp-content/plugins/

# Image Widgets (Why isn't this standard?)
#echo "Fetching Image Widget plugin...";
#wget --quiet http://downloads.wordpress.org/plugin/image-widget.zip;
#unzip -q  image-widget.zip;
#mv image-widget wordpress/wp-content/plugins/

# W3 Total Cache 
#echo "Fetching W3 Total Cache...";
#wget --quiet http://downloads.wordpress.org/plugin/w3-total-cache.zip
#unzip -q  w3-total-cache.zip;
#mv w3-total-cache wordpress/wp-content/plugins/

# Jetpack
#echo "Fetching Jetpack...";
#wget --quiet http://downloads.wordpress.org/plugin/jetpack.2.8.zip
#unzip -q jetpack.2.8.zip
#mv jetpack wordpress/wp-content/plugins/

# Regenerate Thumbnails (good for when you need to make custom sizes)
#echo "Fetching Regenerate Thumbnails...";
#wget --quiet http://downloads.wordpress.org/plugin/regenerate-thumbnails.zip
#unzip -q regenerate-thumbnails.zip
#mv regenerate-thumbnails wordpress/wp-content/plugins/


# WordPress Importer
#echo "Fetching WordPress Importer...";
#wget --quiet http://downloads.wordpress.org/plugin/wordpress-importer.zip
#unzip -q wordpress-importer.zip
#mv wordpress-importer wordpress/wp-content/plugins/


# Simple Page Ordering
#echo "Fetching Simple Page Ordering...";
#wget --quiet http://downloads.wordpress.org/plugin/simple-page-ordering.zip
#unzip -q simple-page-ordering.zip
#mv simple-page-ordering wordpress/wp-content/plugins/

# BackupWPup
#echo "BackupWPup...";
#wget --quiet http://downloads.wordpress.org/plugin/backwpup.zip
#unzip -q backwpup.zip
#mv backwpup wordpress/wp-content/plugins/


# Cleanup
echo "Cleaning up temporary files and directories...";
rm *.zip


# Move stuff into current directory
mv wordpress/* .;
rm -rf wordpress;


echo "Done!";
